---
title: "Untitled"
author: "Renaud Hass"
date: "2023-11-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyverse)
library(dplyr)
library(readxl)
library(ggplot2)
library(tibble)
library(readxl)
library(data.table)
library(openxlsx)
```


Import des bases
Creation d'une variable chemin
```{r}

USER <- Sys.getenv("USERNAME")

if (USER == "reno"){ 
  CHEMIN <- "C:/d\u00e9mo S3/analyse de territoire/DATA/"
}

if (USER == "Tibo"){
  CHEMIN <- "C:/Users/Tibo/Documents/Demographie/M2S1/UE5 - Diagnostic du territoire/"
}

pop_iris <- read.csv2(paste0(CHEMIN, "./data/base-ic-evol-struct-pop-2019.csv")) # base insee
pop_iris  <- pop_iris %>% mutate_all(as.character) %>% mutate_all(as.numeric)
pop_iris  <- pop_iris  %>% mutate( IRIS = as.character( IRIS ), COM = as.character(COM))

correspondance_iris_ems <-  read_excel(paste0(CHEMIN,"./data/table_correspondance_IRIS_EMS.xlsx") , sheet = "EMS") # table de correspondance du leyen

```

```{r}


# création d'une table avec uniquement les iris de l'eurométropole

EMS_pop_iris <- inner_join(pop_iris , correspondance_iris_ems , join_by( IRIS == ID_IRIS))

# création d'une variable boulenne qui prend 1 si le quartier est QPV

EMS_pop_iris <- EMS_pop_iris %>%  mutate(
     QPV = case_when(
       ID_QPV == "NA" ~ 0,
       ID_QPV != "NA" ~ 1))

# Creation d'une table avec que les QPV

QPV_pop_iris <- EMS_pop_iris %>% filter (QPV == "1")

STRAS_pop_iris <- EMS_pop_iris %>% filter(COM =="67482")
        
```

```{r}

# nettoyage des tables pour faire des pyramides

#Selection des variabls a garder

homme_pyr_EMS_pop_iris <- EMS_pop_iris %>% select( P19_POPH , P19_H0014 , P19_H1529 , P19_H3044 , P19_H4559 , P19_H6074 , P19_H75P) 

homme_pyr_QPV_pop_iris <- QPV_pop_iris %>% select( P19_POPH , P19_H0014 , P19_H1529 , P19_H3044 , P19_H4559 , P19_H6074 , P19_H75P)

homme_pyr_Sras_pop_iris <- STRAS_pop_iris %>% select( P19_POPH , P19_H0014 , P19_H1529 , P19_H3044 , P19_H4559 , P19_H6074 , P19_H75P)

femme_pyr_EMS_pop_iris <- EMS_pop_iris %>% select(P19_POPF , P19_F0014 , P19_F1529 , P19_F3044 , P19_F4559 , P19_F6074 , P19_F75P)

femme_pyr_QPV_pop_iris <- QPV_pop_iris %>% select(P19_POPF , P19_F0014 , P19_F1529 , P19_F3044 , P19_F4559 , P19_F6074 , P19_F75P)

femme_pyr_Sras_pop_iris <- STRAS_pop_iris %>% select( P19_POPH , P19_H0014 , P19_H1529 , P19_H3044 , P19_H4559 , P19_H6074 , P19_H75P)

# Calcule de la somme des indicateurs

homme_pyr_EMS_pop <- homme_pyr_EMS_pop_iris %>%
    summarise(across(where(is.numeric), ~ sum(.x * -1, na.rm = TRUE)))

homme_pyr_QPV_pop <- homme_pyr_QPV_pop_iris %>%
    summarise(across(where(is.numeric), ~ sum(.x * -1, na.rm = TRUE))) 

homme_pyr_Stras_pop <- homme_pyr_Sras_pop_iris %>%
    summarise(across(where(is.numeric), ~ sum(.x * -1, na.rm = TRUE))) 

femme_pyr_EMS_pop <- femme_pyr_EMS_pop_iris %>%
    summarise(across(where(is.numeric), ~ sum(.x, na.rm = TRUE))) 

femme_pyr_QPV_pop <- femme_pyr_QPV_pop_iris %>%
    summarise(across(where(is.numeric), ~ sum(.x, na.rm = TRUE))) 

femme_pyr_Stras_pop <- femme_pyr_Sras_pop_iris %>%
    summarise(across(where(is.numeric), ~ sum(.x, na.rm = TRUE))) 


# création d'une dataframe de format HOMME/FEMMe en colone

# Transposition des dataframes



t_homme_pyr_EMS_pop <- t(homme_pyr_EMS_pop)
t_homme_pyr_EMS_pop <- cbind(rownames(t_homme_pyr_EMS_pop), data.frame(t_homme_pyr_EMS_pop, row.names=NULL)) 

t_homme_pyr_QPV_pop <- t(homme_pyr_QPV_pop)
t_homme_pyr_QPV_pop <- cbind(rownames(t_homme_pyr_QPV_pop), data.frame(t_homme_pyr_QPV_pop, row.names=NULL)) 

t_homme_pyr_Stras_pop <- t(homme_pyr_Stras_pop)
t_homme_pyr_Stras_pop <- cbind(rownames(t_homme_pyr_Stras_pop), data.frame(t_homme_pyr_Stras_pop, row.names=NULL)) 

t_femme_pyr_EMS_pop <- t(femme_pyr_EMS_pop)
t_femme_pyr_EMS_pop <- cbind(rownames(t_femme_pyr_EMS_pop), data.frame(t_femme_pyr_EMS_pop, row.names=NULL)) 

t_femme_pyr_QPV_pop <- t(femme_pyr_QPV_pop)
t_femme_pyr_QPV_pop <- cbind(rownames(t_femme_pyr_QPV_pop), data.frame(t_femme_pyr_QPV_pop, row.names=NULL)) 

t_femme_pyr_Stras_pop <- t(femme_pyr_Stras_pop)
t_femme_pyr_Stras_pop <- cbind(rownames(t_femme_pyr_Stras_pop), data.frame(t_femme_pyr_Stras_pop, row.names=NULL)) 

# recodage des tranches d'ages



t_homme_pyr_EMS_pop$classe_age <- c("total" ,"O-14" , "15-29" , "30-44" , "45-59" , "60-74" , "vieux")
t_homme_pyr_EMS_pop <- t_homme_pyr_EMS_pop[,-1]

t_homme_pyr_Stras_pop$classe_age <- c("total" ,"O-14" , "15-29" , "30-44" , "45-59" , "60-74" , "vieux")
t_homme_pyr_Stras_pop <- t_homme_pyr_Stras_pop[,-1]

t_homme_pyr_QPV_pop$classe_age <- c("total" ,"O-14" , "15-29" , "30-44" , "45-59" , "60-74" , "vieux")
t_homme_pyr_QPV_pop <- t_homme_pyr_QPV_pop[,-1]

t_femme_pyr_EMS_pop$classe_age <- c("total" ,"O-14" , "15-29" , "30-44" , "45-59" , "60-74" , "vieux")
t_femme_pyr_EMS_pop <- t_femme_pyr_EMS_pop[,-1]

t_femme_pyr_Stras_pop$classe_age <- c("total" ,"O-14" , "15-29" , "30-44" , "45-59" , "60-74" , "vieux")
t_femme_pyr_Stras_pop <- t_femme_pyr_Stras_pop[,-1]

t_femme_pyr_QPV_pop$classe_age <- c("total" ,"O-14" , "15-29" , "30-44" , "45-59" , "60-74" , "vieux")
t_femme_pyr_QPV_pop <- t_femme_pyr_QPV_pop[,-1]

# jointure des bases

pyr_EMS <- full_join(t_homme_pyr_EMS_pop , t_femme_pyr_EMS_pop , join_by(classe_age) )
pyr_Stras <- full_join(t_homme_pyr_Stras_pop , t_femme_pyr_Stras_pop , join_by(classe_age) )
pyr_Qpv <- full_join(t_homme_pyr_QPV_pop , t_femme_pyr_QPV_pop , join_by(classe_age) )

# changement de l'ordre des colones

pyr_EMS <- pyr_EMS[,c(2,1,3)]
pyr_Stras <- pyr_Stras[,c(2,1,3)]
pyr_Qpv <- pyr_Qpv[,c(2,1,3)]

write.xlsx(pyr_EMS, "./pyr_EMS.xlsx")
write.xlsx(pyr_Stras, "./pyr_Stras.xlsx")
write.xlsx(pyr_Qpv, "./pyr_Qpv.xlsx")
```

Pyramides des ages
```{r}
# tidysation

ggplot(pyr_EMS, aes(x=classe_age))+
        geom_bar(data = subset(TravailMenageCode, SEXE6 == "Femme"))+
        geom_bar(data = subset(TravailMenageCode, SEXE6 == "Homme"), aes(y = ..count..*(-1))) +
        scale_y_continuous(breaks = seq(-60,60,10), labels = abs(seq(-60,60,10))) +
        coord_flip()
```
